### ISSUE TITLE
Add Site to Filter

### ISSUE THREAD

**Issue by ganon69** [acnapyx/paywall-remover#1]
Please add the following site to the filter list:
https://elcomercio.pe

**Comment by acnapyx** [comment]
Sorry for the late reply.

This site doesn't just "hide" the paywalled content, neither limits the number of articles that can be read; it just doesn't show specific, non-public articles that are "subscription only", so it is out of the scope of this project. (The content isn't public, so the paywall they've implemented does it job just like it's supposed to.)

**Comment by ganon69** [comment]
Ok thx for the info
________________________________
